config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :overview, presence: true
  validates :title, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %I[new create]
  before_action :set_bookmark, only: %I[destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %I[show]
  def index
    @lists = List.all
  end

  def show
    @bookmarks = Bookmark.where("list_id = #{params[:id]}")
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.valid?
      @list.save!
      redirect_to list_path(@list)
    else
      render 'lists/new', status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for  [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, label_method: :title, value_method: :id %>
  <%= f.input :list_id, as: :hidden, input_html: { value: params["list_id"] } %>
  <%= f.button :submit %>
<% end %> 

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render "form", list: @list, bookmark: @bookmark %>
<%= link_to 'back', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 position-sticky sticky-top">
    <%= link_to '', lists_path, class: 'logo_nav' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarText">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'New list', new_list_path, class: 'nav-link my_btns' %>
        </li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container-fluid bck_lists d-flex justify-content-center align-items-center">

<h1>Listez n'importe quel film</h1>
</div>
<ul class="lists">
<% @lists.each do |list| %>
<li>
<div class="card_list">
  <div class="card-body d-flex justify-content-center align-items-center">
    <%= link_to list.name, list %>
  </div>
</div>
</li>
<% end %>
<%= render "form", list: @list %>
</ul>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<%= link_to 'back', lists_path %>

app/views/lists/show.html.erb
<h1>List : <%= @list.name %></h1>

<ul>
<% @bookmarks.each do |bookmark| %>
<li>
<%= bookmark.comment %>
<%= link_to 'delete', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: 'Are u sure about that ?'} %>
</li>
<% end %>
</ul>

<%= link_to 'back', lists_path %>